policy:
  description: ""
  default_state: hot
  states:
    - name: hot
      actions:
        - retry:
            count: 3
            backoff: exponential
            delay: 1m
          rollover:
            min_index_age: 3d
            min_primary_shard_size: 48gb
      transitions:
        - state_name: warm
          conditions:
            min_rollover_age: 3d
    - name: warm
      actions:
        - retry:
            count: 3
            backoff: exponential
            delay: 1m
          read_only: {}
      transitions:
        - state_name: delete
          conditions:
            min_index_age: 4d
    - name: delete
      actions:
        - retry:
            count: 3
            backoff: exponential
            delay: 1m
          delete: {}
      transitions: []
  ism_template:
    - index_patterns:
        - trace_*

        # The policy that the Data Prepper installs for otel-v1-apm-span-* does
        # not delete traces so this policy overrules the shipped policy.
        # We don’t want to disable Data Prepper creation of the policy because
        # that would also disable the creation of the index template which we
        # currently want to have managed.
        - otel-*-apm-span-*

      priority: 100
