policy:
  description: ""
  default_state: hot
  states:
    - name: hot
      actions:
        - retry:
            count: 3
            backoff: exponential
            delay: 1m
          rollover:
            min_index_age: 185d
            min_primary_shard_size: 48gb
      transitions:
        - state_name: warm
          conditions:
            min_rollover_age: 7d
    - name: warm
      actions:
        - retry:
            count: 3
            backoff: exponential
            delay: 1m
          read_only: {}
      transitions:
        - state_name: delete
          conditions:
            min_index_age: 190d
    - name: delete
      actions:
        - retry:
            count: 3
            backoff: exponential
            delay: 1m
          delete: {}
      transitions: []
  ism_template:
    - index_patterns:
        - log_opnsense_*
        - log_fortinet_*
      priority: 100
