policy:
  description: ""
  default_state: hot
  states:
    - name: hot
      actions:
        - retry:
            count: 3
            backoff: exponential
            delay: 1m
          rollover:
            min_index_age: 85d
            min_primary_shard_size: 48gb
      transitions:
        - state_name: warm
          conditions:
            min_rollover_age: 7d
    - name: warm
      actions:
        - retry:
            count: 3
            backoff: exponential
            delay: 1m
          read_only: {}
      transitions:
        - state_name: delete
          conditions:
            min_index_age: 90d
    - name: delete
      actions:
        - retry:
            count: 3
            backoff: exponential
            delay: 1m
          delete: {}
      transitions: []
  ism_template:
    - index_patterns:
        - log_haproxy_*
        - log_small_*
      priority: 100
