apiVersion: k8s.keycloak.org/v2alpha1
kind: Keycloak
metadata:
  name: keycloak
spec:
  db:
    database: keycloak
    host: keycloak-primary
    passwordSecret:
      key: password
      name: keycloak-pguser-keycloak
    usernameSecret:
      key: user
      name: keycloak-pguser-keycloak
    vendor: postgres
  hostname:
    hostname: auth.{{ .Values.global.clusterDomain }}
  http:
    tlsSecret: keycloak-tls
  ingress:
    enabled: false
  instances: 1
