apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: product-logging
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    path: base-manifests
    repoURL: https://github.com/fabriziowho/test-argocd-kafka.git
    targetRevision: master
  syncPolicy:
    automated: {}
