config:
  opensearch:
    version: 2.4.1
    plugins:
      - repository-s3
      - repository-azure
      - https://github.com/aiven/prometheus-exporter-plugin-for-opensearch/releases/download/2.4.1.0/prometheus-exporter-2.4.1.0.zip
    nodePools:
      data_a:
        count: 1
        diskSize: 30Gi
        memory:
          request: 4Gi
          limit: 4Gi
        cpu:
          request: 100m
          limit: 1
      data_b:
        count: 1
        diskSize: 30Gi
        memory:
          request: 4Gi
          limit: 4Gi
        cpu:
          request: 100m
          limit: 1
      # ingest:
      #   count: 2
      #   diskSize: 30Gi
      #   memory:
      #     request: 4Gi
      #     limit: 4Gi
      #   cpu:
      #     request: 100m
      #     limit: 1

role:
  example:
    clusterPermissions:
      - cluster_composite_ops
      - indices_monitor
    indexPermissions:
      - indexPatterns:
          - movies*
        dls: ""
        fls: []
        allowedActions:
          - read
    tenantPermissions:
      - tenantPatterns:
          - human_resources
        allowedActions:
          - kibana_all_read
