apiVersion: v1
kind: ConfigMap
metadata:
  name: ilm-config
data:
  {{- (.Files.Glob "config/common/ilm/**.yaml").AsConfig | nindent 2 }}

  {{- $ilmpath := printf "config/%s/ilm/**.yaml" .Values.global.cluster.environment  }}
  {{- range $k, $v := ((.Files.Glob $ilmpath).AsConfig | fromYaml) }}
  {{ $.Values.global.cluster.environment }}-{{ $k }}: |
    {{- $v | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: roles-config
data:
  {{- (.Files.Glob "config/common/roles/**.yaml").AsConfig | nindent 2 }}

  {{- $rolespath := printf "config/%s/roles/**.yaml" .Values.global.cluster.environment  }}
  {{- range $k, $v := ((.Files.Glob $rolespath).AsConfig | fromYaml) }}
  {{ $.Values.global.cluster.environment }}-{{ $k }}: |
    {{- $v | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rolesmapping-config
data:
  {{- (.Files.Glob "config/common/rolesmapping/**.yaml").AsConfig | nindent 2 }}

  {{- $rolesmappingpath := printf "config/%s/rolesmapping/**.yaml" .Values.global.cluster.environment  }}
  {{- range $k, $v := ((.Files.Glob $rolesmappingpath).AsConfig | fromYaml) }}
  {{ $.Values.global.cluster.environment }}-{{ $k }}: |
    {{- $v | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: indextemplates-config
data:
  {{- (.Files.Glob "config/common/indextemplates/**.yaml").AsConfig | nindent 2 }}

  {{- $indextemplatespath := printf "config/%s/indextemplates/**.yaml" .Values.global.cluster.environment  }}
  {{- range $k, $v := ((.Files.Glob $indextemplatespath).AsConfig | fromYaml) }}
  {{ $.Values.global.cluster.environment }}-{{ $k }}: |
    {{- $v | nindent 4 }}
  {{- end }}
