apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-exporter
  labels:
    release: kube-prometheus-stack
spec:
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  podMetricsEndpoints:
    - basicAuth:
        password:
          key: password
          name: admin-secret
        username:
          key: username
          name: admin-secret
      path: /_prometheus/metrics
      port: http
      scheme: https
      tlsConfig:
        insecureSkipVerify: true
  selector:
    matchLabels:
      opster.io/opensearch-cluster: opensearch-cluster
