{{- range $name, $config := .Values.config.role }}
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: {{ $name }}
spec:
  opensearchCluster:
    name: {{ .Release.Name }}
  clusterPermissions:
  {{- range $.Values.config.opensearch.roles.example.clusterPermissions }}
    - {{ . }}
  {{- end }}
  indexPermissions:
  {{- range $.Values.config.opensearch.roles.example.indexPermissions }}
    - {{ . }}
  {{- end }}
  tenantPermissions:
    - tenantPatterns:
        - human_resources
      allowedActions:
        - kibana_all_read
---
apiVersion: opensearch.opster.io/v1
kind: OpensearchRole
metadata:
  name: example
  namespace: opensearch
spec:
  opensearchCluster:
    name: my-first-cluster
  clusterPermissions:
    - cluster_composite_ops
    - indices_monitor
  indexPermissions:
    - indexPatterns:
        - movies*
      dls: ""
      fls: []
      allowedActions:
        - read
  tenantPermissions:
    - tenantPatterns:
        - human_resources
      allowedActions:
        - kibana_all_read
