{{- range $name, $config := .Values.config.kafka.listeners }}
{{- if $config.certManager }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: listener-{{ $name }}-tls
spec:
  dnsNames:
    - {{ $config.namePrefix }}-bootstrap.test
    {{- range $i, $e := until ($.Values.config.kafka.replicas | int) }}
    - {{ $config.namePrefix }}-broker-{{ $i }}.test
    {{- end}}
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: letsencrypt-prod
  secretName: listener-{{ $name }}-tls
{{- end }}
{{- end }}
